spring:
  application:
    name: Taco Cloud
  thymeleaf:
    cache: true
  datasource:
    generate-unique-name: false
    name: tacocloud
  main:
      allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ea9738c692f73731ea2d
            clientSecret: b51de12eec232fa9a99e519d42954e88f4765c61
            scope: email, public_profile
  config:
    activate:
      on-profile: dev
server:
  port: 8443
  ssl:
    key-store: classpath:mykeys.jks
    key-password: fofana
    key-store-password: fofana
logging:
  level:
    root: DEBUG
    org.springframework.security: DEBUG

greeting:
  welcome: You are using ${spring.application.name}
taco:
  orders:
    pageSize: 10
